// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// instabilityQuantileTopEst
double instabilityQuantileTopEst(double alpha, double fi, double delta, double sigma, double kappa, double a, double b, double k);
RcppExport SEXP _instabilityTest_instabilityQuantileTopEst(SEXP alphaSEXP, SEXP fiSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP kappaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(instabilityQuantileTopEst(alpha, fi, delta, sigma, kappa, a, b, k));
    return rcpp_result_gen;
END_RCPP
}
// genWk
double genWk(double fi, double delta, double sigma, double kappa, double a, double b, Rcpp::NumericVector u);
RcppExport SEXP _instabilityTest_genWk(SEXP fiSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP kappaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type fi(fiSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(genWk(fi, delta, sigma, kappa, a, b, u));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_instabilityTest_instabilityQuantileTopEst", (DL_FUNC) &_instabilityTest_instabilityQuantileTopEst, 8},
    {"_instabilityTest_genWk", (DL_FUNC) &_instabilityTest_genWk, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_instabilityTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
