# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib instabilityTest, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

genWk <- function(w, fi, delta, sigma, kappa, a, b, u) {
    .Call(`_instabilityTest_genWk`, w, fi, delta, sigma, kappa, a, b, u)
}

