# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findZ <- function(alpha, w, fi, kappa, delta, sigma, tau) {
    .Call(`_instabilityTest_findZ`, alpha, w, fi, kappa, delta, sigma, tau)
}

#' instabilityQuantile
#' @description Calculation of a quantile with given parameters for a random variable stochastically dominating over a Markov chain.
#' @param alpha the significance level.
#' @param w initial state of Markov chain.
#' @param fi upper estimate for the absolute value of Markov chain increment in one step.
#' @param delta the downward drift that a process must exhibit in order to be stable.
#' @param sigma the lower estimate for the number of steps.
#' @param kappa the lower estimate for initial state.
#' @param a a parameter for time calculation. Time is calculated by a formula: a*(X_{i-1})+b.
#' @param b b parameter for time calculation. Time is calculated by a formula: a*(X_{i-1})+b.
#' @param k number of steps to select a new point.
#' @return Quantile with given parameters
instabilityQuantile <- function(alpha, w, fi, delta, sigma, kappa, a, b, k) {
    .Call(`_instabilityTest_instabilityQuantile`, alpha, w, fi, delta, sigma, kappa, a, b, k)
}

